/**
 * Error codes for E-Y project
 * Format: DOMAIN_ERROR_TYPE
 */

export const ERROR_CODES = {
  // Wallet errors
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INVALID_ADDRESS: 'WALLET_INVALID_ADDRESS',
  WALLET_INVALID_MNEMONIC: 'WALLET_INVALID_MNEMONIC',

  // BLIK errors
  BLIK_CODE_EXPIRED: 'BLIK_CODE_EXPIRED',
  BLIK_CODE_INVALID: 'BLIK_CODE_INVALID',
  BLIK_CODE_ALREADY_USED: 'BLIK_CODE_ALREADY_USED',
  BLIK_CODE_NOT_FOUND: 'BLIK_CODE_NOT_FOUND',
  BLIK_INVALID_AMOUNT: 'BLIK_INVALID_AMOUNT',

  // Transaction errors
  TX_FAILED: 'TX_FAILED',
  TX_REJECTED_BY_USER: 'TX_REJECTED_BY_USER',
  TX_INSUFFICIENT_GAS: 'TX_INSUFFICIENT_GAS',
  TX_NONCE_TOO_LOW: 'TX_NONCE_TOO_LOW',

  // Network errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  RPC_ERROR: 'RPC_ERROR',

  // Username errors
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  USERNAME_NOT_FOUND: 'USERNAME_NOT_FOUND',
  USERNAME_INVALID_FORMAT: 'USERNAME_INVALID_FORMAT',

  // Business errors
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BUSINESS_INVALID_SHARES: 'BUSINESS_INVALID_SHARES',
  BUSINESS_QUORUM_NOT_REACHED: 'BUSINESS_QUORUM_NOT_REACHED',
  BUSINESS_PROPOSAL_EXPIRED: 'BUSINESS_PROPOSAL_EXPIRED',
  BUSINESS_ALREADY_VOTED: 'BUSINESS_ALREADY_VOTED',
  BUSINESS_NOT_MEMBER: 'BUSINESS_NOT_MEMBER',
  BUSINESS_DEPLOY_FAILED: 'BUSINESS_DEPLOY_FAILED',

  // General errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
